@server = http://localhost:3005

### 트랜잭션 실행
POST {{server}}/transaction HTTP/1.1
Content-Type: application/json

{
    "privateKey": "{{$dotenv PRIVATE_KEY}}",
    "receiver": "0xceCD415ceC15Fd08140f215c48116C42B8618f43",
    "amount": "0.01"
}

### 프로바이더 확인
GET {{server}}/transaction HTTP/1.1

### 프로바이더 변경
PUT {{server}}/transaction HTTP/1.1
Content-Type: application/json

{
    "providerName": "ganache"
}

### 잔액 확인
GET {{server}}/transaction/0xfAD153d059F9dA994F1688b3333f2Fb415682a14