@server = {{$dotenv PROTOCOL}}://{{$dotenv HOST}}:{{$dotenv PORT}}/market

### NFT 컬렉션들을 가져옵니다.
GET {{server}} HTTP/1.1

// metadata: ipfs://QmVXbeGajzbAAVk5rw9CQmysAbBUz6SHBiT2RLj4HbmsBt


### CA를 기준으로 NFT들을 가져옵니다.
POST {{server}} HTTP/1.1
Content-Type: application/json

{
    "ca": "0x5d5709E5BEaE948a4B68967607B8dE304197A951"
}
### EOA를 기준으로 NFT들을 가져옵니다.
POST {{server}}/user HTTP/1.1
Content-Type: application/json

{
    "eoa": "0xFA2e0fBBE47B0dbe0B3c4caD0cC81a57F8A663d3"
}

### CA와 TokenId를 받아 해당 NFT의 트랜잭션 기록을 보여줍니다.
POST {{server}}/transaction HTTP/1.1
Content-Type: application/json

{
    "ca": "0x5d5709E5BEaE948a4B68967607B8dE304197A951",
    "tokenId": 1
}

### CA와 TokenId를 받아 해당 NFT의 정보를 보여줍니다.
POST {{server}}/info HTTP/1.1
Content-Type: application/json

{
    "ca": "0x5d5709E5BEaE948a4B68967607B8dE304197A951",
    "tokenId": 1
}

### 네트워크에 따라 화폐를 변경합니다.
POST {{server}}/currency HTTP/1.1
Content-Type: application/json

{
    "symbol": "matic"
}


### NFT 테스트
PUT {{server}} HTTP/1.1
Content-Type: application/json

{
    "ca": "0x468613F44FA1a55bEC3F139539F9abB746726DB0",
    "tokenId": 2
}

# ipfs://bafybeifvbaj3l3ilz37qz5rhp5xniq5mrypv4wl77zhpgqlibojz4esdpq/1