@server = {{$dotenv PROTOCOL}}://{{$dotenv HOST}}:{{$dotenv PORT}}/trends

### 코인 목록
GET {{server}} HTTP/1.1

### 코인 정보
POST {{server}} HTTP/1.1
Content-Type: application/json

{
    "symbol": "eth"
}

### 환율 정보
GET {{server}}/exchange?to=kRw,usd HTTP/1.1
