@server = http://localhost:3005

### 니모닉 생성
GET {{server}}/account/mnemonic  HTTP/1.1
Content-Type: application/json

### 니모닉 계정 생성
POST {{server}}/account/mnemonic HTTP/1.1
Content-Type: application/json

{
    "mnemonic":["chief","like","unveil","elite","void","mixed","ball","ribbon","pipe","disagree","where","wear"]
}

### 사용자 닉네임 저장
POST {{server}}/account HTTP/1.1
Content-Type: application/json

{
    "address":"0x0000000000000000000000000000000000000000",
    "nickname":"address1"
}