name: Deploy to Back Test Server

on:
  push:
    branches:
      - dev
    paths:
      - "back/**"

jobs:
  back_deploy:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install node lts
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install --lts

      - name: Install Dependencies & Test
        run: |
          npm install
          npm run test

      - name: Build
        run: |
          npm run build

      - name: SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.BACK_TEST_SERVER}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.BACK_TEST_SERVER_PRIVATE_KEY}}
          source: "back/dist/*,back/package.json"
          target: "www"
          strip_components: 1
      - name: Run Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.BACK_TEST_SERVER}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.BACK_TEST_SERVER_PRIVATE_KEY}}
          port: ${{secrets.PORT}}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /home/ubuntu/www
            pm2 delete all
            mv dist/* . && rmdir dist
            npm install
            pm2 start main.js
