@server = http://localhost:3000

### 토큰 추가하기
POST {{server}}/token?network=ethereum HTTP/1.1
Content-Type: application/json

{
    "ca": "0xb8c77482e45f1f44de1745f52c74426c631bdd52",
    "symbol": "bnb",
    "decimal": 18
}